#!/bin/bash

# Accept the project name as CLI argument
PROJECT_NAME=${1:-example-app}

docker info > /dev/null 2>&1

# Ensure that Docker is running...
if [ $? -ne 0 ]; then
    echo "Docker is not running."

    exit 1
fi

docker run --rm \
    -v "$(pwd)":/opt \
    -w /opt \
    azzazkhan/devcontainer-laravel:php-8.3 \
    root bash -c "composer create-project laravel/laravel ${PROJECT_NAME} --no-interaction"

cd ${PROJECT_NAME}

CYAN='\033[0;36m'
LIGHT_CYAN='\033[1;36m'
BOLD='\033[1m'
NC='\033[0m'

echo ""

if sudo -n true 2>/dev/null; then
    sudo chown -R $USER: .
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/azzazkhan/devcontainer-laravel/master/install)"
    echo -e "${BOLD}Get started with:${NC} cd ${PROJECT_NAME} && sail up"
else
    echo -e "${BOLD}Please provide your password so we can make some final adjustments to your application's permissions.${NC}"
    echo ""
    sudo chown -R $USER: .
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/azzazkhan/devcontainer-laravel/master/install)"
    echo ""
    echo -e "${BOLD}Thank you! We hope you build something incredible. Dive in with:${NC} cd ${PROJECT_NAME} && sail up"
fi
