services:
    app:
        image: azzazkhan/devcontainer-laravel:php-8.3
        restart: unless-stopped
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        # ports:
        #     - '${APP_PORT:-80}:80'
        #     - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER:-1000}'
            WWWGROUP: '${WWWGROUP:-1000}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www'
        networks:
            - sail
            - traefik
        depends_on:
            - mysql
            - redis
            - mailpit
            - meilisearch
            - minio
            - soketi
            - open-observe
        labels:
            - traefik.enable=true
            - traefik.http.routers.laravel.rule=Host(`laravel.localhost`)
            - traefik.http.routers.laravel.entrypoints=web
            - traefik.http.services.laravel-service.loadbalancer.server.port=80

    mysql:
        image: mysql:8
        restart: unless-stopped
        # ports:
        #     - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD:-password}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE:-laravel}'
            MYSQL_USER: '${DB_USERNAME:-sail}'
            MYSQL_PASSWORD: '${DB_PASSWORD:-password}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'sail-mysql:/var/lib/mysql'
            - './docker/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD:-password}'
            retries: 3
            timeout: 5s

    redis:
        image: redis:7.4-alpine
        restart: unless-stopped
        # ports:
        #     - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sail-redis:/data'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s

    mailpit:
        image: axllent/mailpit:v1.20.4
        restart: unless-stopped
        # ports:
        #     - '${FORWARD_MAILPIT_PORT:-1025}:1025'
        #     - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
        environment:
            MP_DATABASE: /data/mailpit.db
        volumes:
            - sail-mailpit:/data
        networks:
            - sail
            - traefik
        labels:
            - traefik.enable=true
            - traefik.http.routers.laravel-mailpit.rule=Host(`mailpit.laravel.localhost`)
            - traefik.http.routers.laravel-mailpit.entrypoints=web
            - traefik.http.services.laravel-mailpit-service.loadbalancer.server.port=8025

    phpmyadmin:
        image: phpmyadmin:5.2.1-apache
        restart: unless-stopped
        # ports:
        #     - '${FORWARD_PMA_PORT:-8080}:80'
        environment:
            PMA_ABSOLUTE_URI: http://phpmyadmin.laravel.localhost
            PMA_HOST: mysql
            PMA_PORT: 3306
            PMA_USER: root
            PMA_PASSWORD: ${DB_PASSWORD:-password}
            UPLOAD_LIMIT: 100M
        networks:
            - sail
            - traefik
        depends_on:
            - mysql
        labels:
            - traefik.enable=true
            - traefik.http.routers.laravel-phpmyadmin.rule=Host(`phpmyadmin.laravel.localhost`)
            - traefik.http.routers.laravel-phpmyadmin.entrypoints=web
            - traefik.http.services.laravel-phpmyadmin-service.loadbalancer.server.port=80

    meilisearch:
        image: 'getmeili/meilisearch:latest'
        restart: unless-stopped
        # ports:
        #     - '${FORWARD_MEILISEARCH_PORT:-7700}:7700'
        environment:
            MEILI_NO_ANALYTICS: '${MEILISEARCH_NO_ANALYTICS:-false}'
        volumes:
            - 'sail-meilisearch:/meili_data'
        networks:
            - sail
            - traefik
        healthcheck:
            test: ['CMD', 'wget', '--no-verbose', '--spider', 'http://localhost:7700/health']
            retries: 3
            timeout: 5s
        labels:
            - traefik.enable=true
            - traefik.http.routers.laravel-meilisearch.rule=Host(`meilisearch.laravel.localhost`)
            - traefik.http.routers.laravel-meilisearch.entrypoints=web
            - traefik.http.services.laravel-meilisearch-service.loadbalancer.server.port=7700

    minio:
        image: 'minio/minio:latest'
        restart: unless-stopped
        # ports:
        #     - '${FORWARD_MINIO_PORT:-9000}:9000'
        #     - '${FORWARD_MINIO_CONSOLE_PORT:-8900}:8900'
        environment:
            MINIO_ROOT_USER: '${MINIO_USER:-sail}'
            MINIO_ROOT_PASSWORD: '${MINIO_PASSWORD:-password}'
        volumes:
            - 'sail-minio:/data/minio'
        networks:
            - sail
            - traefik
        command: minio server /data/minio --console-address ":8900"
        healthcheck:
            test: ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
            retries: 3
            timeout: 5s
        labels:
            - traefik.enable=true
            # - traefik.http.routers.laravel-minio.rule=Host(`minio.laravel.localhost`)
            # - traefik.http.routers.laravel-minio.entrypoints=web
            # - traefik.http.routers.laravel-minio.service=laravel-minio-service
            # - traefik.http.services.laravel-minio-service.loadbalancer.server.port=9000
            - traefik.http.routers.laravel-minio-console.rule=Host(`console.minio.laravel.localhost`)
            - traefik.http.routers.laravel-minio-console.entrypoints=web
            - traefik.http.routers.laravel-minio-console.service=laravel-minio-console-service
            - traefik.http.services.laravel-minio-console-service.loadbalancer.server.port=8900

    soketi:
        image: 'quay.io/soketi/soketi:latest-16-alpine'
        restart: unless-stopped
        # ports:
        #     - '${PUSHER_PORT:-6001}:6001'
        #     - '${PUSHER_METRICS_PORT:-9601}:9601'
        environment:
            SOKETI_DEBUG: '${SOKETI_DEBUG:-1}'
            SOKETI_METRICS_SERVER_PORT: '9601'
            SOKETI_DEFAULT_APP_ID: '${PUSHER_APP_ID:-laravel}'
            SOKETI_DEFAULT_APP_KEY: '${PUSHER_APP_KEY:-app_key}'
            SOKETI_DEFAULT_APP_SECRET: '${PUSHER_APP_SECRET:-app_secret}'
        networks:
            - sail
            - traefik
        labels:
            - traefik.enable=true
            - traefik.http.routers.laravel-soketi.rule=Host(`soketi.laravel.localhost`)
            - traefik.http.routers.laravel-soketi.entrypoints=web
            - traefik.http.routers.laravel-soketi.service=laravel-soketi-service
            - traefik.http.services.laravel-soketi-service.loadbalancer.server.port=6001
            - traefik.http.routers.laravel-soketi-metrics.rule=Host(`metrics.soketi.laravel.localhost`)
            - traefik.http.routers.laravel-soketi-metrics.entrypoints=web
            - traefik.http.routers.laravel-soketi-metrics.service=laravel-soketi-metrics-service
            - traefik.http.services.laravel-soketi-metrics-service.loadbalancer.server.port=9601

    open-observe:
        image: public.ecr.aws/zinclabs/openobserve:latest
        restart: unless-stopped
        # ports:
        #     - '${FORWARD_OPEN_OBSERVE_PORT:-5080}:5080'
        environment:
            ZO_DATA_DIR: /data
            ZO_ROOT_USER_EMAIL: ${ZO_ROOT_USER_EMAIL:-test@example.com}
            ZO_ROOT_USER_PASSWORD: ${ZO_ROOT_USER_PASSWORD:-password}
        volumes:
            - sail-open-observe:/data
        networks:
            - sail
            - traefik
        labels:
            - traefik.enable=true
            - traefik.http.routers.laravel-open-observe.rule=Host(`open-observe.laravel.localhost`)
            - traefik.http.routers.laravel-open-observe.entrypoints=web
            - traefik.http.services.laravel-open-observe-service.loadbalancer.server.port=5080

networks:
    sail:
        driver: bridge
    traefik:
        external: true

volumes:
    sail-mysql:
        driver: local
    sail-redis:
        driver: local
    sail-mailpit:
        driver: local
    sail-open-observe:
        driver: local
    sail-meilisearch:
        driver: local
    sail-minio:
        driver: local
