#!/bin/bash

if [ ! -d ".devcontainer" ]; then
    mkdir .devcontainer
fi

if [ ! -d "docker" ]; then
    mkdir docker
fi

curl -sSL https://github.com/azzazkhan/devcontainer-laravel/raw/master/.devcontainer/devcontainer.json -o .devcontainer/devcontainer.json
curl -sSLO https://github.com/azzazkhan/devcontainer-laravel/raw/master/docker-compose.yml
curl -sSL https://github.com/azzazkhan/devcontainer-laravel/raw/master/docker/create-testing-database.sh -o docker/create-testing-database.sh
curl -sSLO https://github.com/azzazkhan/devcontainer-laravel/raw/master/sail

chmod +x sail

echo "Sail files scaffoled succesfully!"
echo ""
