#!/usr/bin/env bash

WWWUSER=${WWWUSER:-1000}

usermod -u $WWWUSER sail

if [ ! -d /.composer ]; then
    mkdir /.composer
fi

chmod -R ugo+rw /.composer

(chown -R $WWWUSER:$WWWUSER /var/www 2>/dev/null || true) &

if [ $# -gt 0 ]; then
    exec gosu $WWWUSER "$@"
else
    exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
fi
