name: Run application test cases
on:
    push:
        branches:
            - master

env:
    REPO_NAME: azzazkhan/laravel-devcontainer
    IMAGE_TAG: php-8.3

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: azzazkhan
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build image
              run: docker build -t ${{ env.REPO_NAME }}:${{ env.IMAGE_TAG }} ./docker

            - name: Push image to container registry
              run: docker push ${{ env.REPO_NAME }}:${{ env.IMAGE_TAG }}
